name: Notion Auto Posting

on:
  schedule:
    - cron: '0 0 * * *' # 매일 오전 9시 (KST 기준)
  workflow_dispatch:

jobs:
  post-to-notion:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 클론
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 의존성 설치
        run: |
          pip install requests markdown

      - name: Notion 업로드 스크립트 실행
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python scripts/notion_uploader.py

